SET NAMES utf8mb4;
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

DROP SCHEMA IF EXISTS sakila;
CREATE SCHEMA sakila;
USE uas202410103031;

--
-- Table structure for table `mobil`
--

CREATE TABLE mobil (
  id SMALLINT INT(11) NOT NULL AUTO_INCREMENT,
  nama VARCHAR(200) NOT NULL,
  jenis VARCHAR(200) NOT NULL,
  PRIMARY KEY (id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Table structure for table `terjual`
--

CREATE TABLE terjual (
  id SMALLINT INT(11) NOT NULL AUTO_INCREMENT,
  jumlah_terjual INT(11) NOT NULL,
  mobil_id INT(11) NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (mobil_id),
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
--
